export const ListAptosData = [
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },

    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Vacunado",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },
    {
        COD: "#12323",
        NOMBRE: "HACHIKO",
        PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
        ESPECIE: "10 Feb 2021",
        ESTADO: "Pendiente",
        ACCIONES: "detalles",
    },

];
