export const inventoaryData = [
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN ",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",

    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",

    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN ",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",

    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",

    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN ",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",

    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",

    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Activo",
    ACCIONES: "Ver detalles",
  },
  {
    SKU: "02694001",
    PRODUCTO: "PARACETAMOL 500MG TABLETA",
    PRESENTACIÓN: "CAJA 100 UN",
    PRECIO: "$ 10.00",
    CATEGORÍA: "BIENESTAR",
    STOCK: "41",
    ESTADO: "Inactivo",
    ACCIONES: "Ver detalles",
  },
];
