export const vaccinationData = [
  {
    COD: "#12323",
    TIPO: "VAC DE RABIA",
    EXPLORACIÓN: "APTO",
    FVACUNACIÓN: "10 Feb 2021",
    FVALIDEZ: "10 Feb 2021",
    ESTADO: "Pendiente",
  },
  {
    COD: "#12323",
    TIPO: "VAC DE RABIA",
    EXPLORACIÓN: "NO APTO",
    FVACUNACIÓN: "10 Feb 2021",
    FVALIDEZ: "10 Feb 2021",
    ESTADO: "Rechazada",
  },
  {
    COD: "#12323",
    TIPO: "VAC DE RABIA",
    EXPLORACIÓN: "APTO",
    FVACUNACIÓN: "10 Feb 2021",
    FVALIDEZ: "10 Feb 2021",
    ESTADO: "Vacunado",
  },
  {
    COD: "#12323",
    TIPO: "VAC DE RABIA",
    EXPLORACIÓN: "APTO",
    FVACUNACIÓN: "10 Feb 2021",
    FVALIDEZ: "10 Feb 2021",
    ESTADO: "Vacunado",
  },
  {
    COD: "#12323",
    TIPO: "VAC DE RABIA",
    EXPLORACIÓN: "APTO",
    FVACUNACIÓN: "10 Feb 2021",
    FVALIDEZ: "10 Feb 2021",
    ESTADO: "Vacunado",
  },
];
