export const proximasData = [
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
  
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
    {
      COD: "#P12321",
      MASCOTAS: "HACHIKO",
      VETERINARIO: "DR. APELLIDOS DE DOCTOR",
      HORARIO: "9:15 - 9:45",
      FECHA: "10 Feb 2021",
      ACCIONES: "Ver detalles",
    },
  ];
  