export const mascotasData = [
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",

    ACCIONES: "Ver detalles",
  },
  {
    ID: "#12323",
    NOMBRE: "HACHIKO",
    PROPIETARIO: "CUBAS TORRES, CARLOS ENRIQUE DE LA VEGA",
    ESPECIE: "CANINO",
    SEXO: "MACHO",
    EDAD: "5",
    star: "bi bi-star-fill grey",
    ESTADO: "Completado",

    ACCIONES: "Ver detalles",
  },
];
