export const RolesData = [
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Administrador",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },
    {
        COD: "#12323",
        NOMBRE: "NOMBRE COMPLETO DE ADMIN",
        USUARIO: "Atención",
        CORREO: "ejemplo@gmail.com",
        UCONEXION: "10 Nov 2023, 2:40 pm",
        DETALLES: "Acción",
    },

];
